### ISSUE TITLE
nodeSelector value is incorrectly formatted by ansible

### ISSUE THREAD

**Issue by pfox1969** [PaloAltoNetworks/prisma-cloud-compute-operator#22]
## Describe the bug

When supplying a nodeSelector the ansible must parse the input into twistcli acceptable format.
twistcli expects the nodeSelector value to be in the _key: "value"_ format.

## Expected behavior

nodeSelector should be created correctly in the twistlock_defender.yaml
```
      serviceAccountName: twistlock-service
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "node-iverson-pfox-lab-twistlock-com"
      containers:
      - name: twistlock-defender
```
## Current behavior

1) set consoledefender.yaml defender.config.nodeLabels value
```
---
apiVersion: pcc.paloaltonetworks.com/v1alpha1
kind: ConsoleDefender
metadata:
  name: pcc-consoledefender
  namespace: twistlock
spec:
  namespace: twistlock
  orchestrator: kubernetes
  version: '21_08_514'
  consoleConfig:
    serviceType: ClusterIP
  defenderConfig:
    docker: true
    nodeLabels: 'kubernetes.io/hostname: "node-iverson-pfox-lab-twistlock-com"'
```

2) Deploy Console and Defenders via Operator
```
kubectl apply -f ./consoledefender.yaml
```

3) View the logs of the Operator container, the [Create Defender YAML task ](https://github.com/PaloAltoNetworks/prisma-cloud-compute-operator/blob/834f36ca889e57938f8fe2d13d6d01ee2763df23/roles/consoledefender/tasks/main.yml#L84)incorrectly passes the _--nodeSelector_ parameter
```
["linux/twistcli", "defender", "export", "kubernetes", "--user", "pierre", "--password", "woof", "--address", "https://twistlock-console.twistlock:8083", "--cluster-address", "twistlock-console", "--monitor-service-accounts", "--namespace", "twistlock", "--nodeSelector", "kubernetes.io/hostname:", "node-iverson-pfox-lab-twistlock-com", "--output", "/opt/ansible/twistlock/twistlock_defender.yaml"]
```
The correct format should be:
```
--nodeSelector 'kubernetes.io/hostname: "node-iverson-pfox-lab-twistlock-com"'
```

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:
