### ISSUE TITLE
Allow Defaults for Console and Defender Configs

### ISSUE THREAD

**Issue by hi-artem** [PaloAltoNetworks/prisma-cloud-compute-operator#27]
### Is your feature request related to a problem?

Not really a problem, but it would be nice to have this feature. 

In a nutshell, the current operator will fail if the config looks something like that:

```yaml
---
apiVersion: pcc.paloaltonetworks.com/v1alpha1
kind: ConsoleDefender
metadata:
  name: pcc-consoledefender
  namespace: twistlock
spec:
  namespace: twistlock
  version: '21_08_520'
```

However, it would be better to just have the default settings applied to both `defenderConfig` and `consoleConfig`.

### Describe the solution you'd like

See example above. I think this can either be done through setting defaults in Ansible, or in CRD OpenAPI scheme.
